services:
    oro_cybersource.integration.channel:
        class: 'Oro\Bundle\CyberSourceBundle\Integration\CyberSourceChannelType'
        tags:
            - { name: oro_integration.channel, type: oro_cybersource }

    oro_cybersource.integration.transport:
        class: 'Oro\Bundle\CyberSourceBundle\Integration\CyberSourceTransport'
        tags:
            - { name: oro_integration.transport, type: oro_cybersource, channel_type: oro_cybersource }
